{
    orders(first:1){
        edges{
            node{
                id
                order_number:name
                customer{
                    id
                    email
                    customer_number:metafield(namespace: "custom", key:"customer_number") {
                        value
                    }
                    tax_exempt_id:metafield(namespace: "custom", key: "tax_exept_id") {
                        value
                    }
                }
                billingAddress{
                    firstName
                    lastName
                    phone
                    address1
                    address2
                    city
                    state:province
                    zip
                    countryCodeV2
                    region:provinceCode
                    company
                }
                billingAddressMatchesShippingAddress
                shippingAddress{
                    firstName
                    lastName
                    phone
                    address1
                    address2
                    city
                    state:province
                    zip
                    countryCodeV2
                    region:provinceCode
                    company
                }
                paymentTerms{
                    paymentTermsName
                    paymentTermsType
                }
                phone
                email
                createdAt
                processedAt
                closedAt
                subtotalPriceSet{
                    presentmentMoney{
                        amount
                        currencyCode
                    }
                }
                totalTaxSet{
                    presentmentMoney{
                        amount
                        currencyCode
                    }
                }
                totalShippingPriceSet{
                    presentmentMoney{
                        amount
                        currencyCode
                    }
                }
                totalPriceSet{
                    presentmentMoney{
                        amount
                        currencyCode
                    }
                }
                lineItems(first: 250) {
                    nodes{
                        id
                        product{
                            title
                            handle
                        }
                        variant{
                            title
                            sku
                            price
                            weight
                        }
                        quantity
                    }
                }
            }
        }
        pageInfo{
            hasNextPage
            endCursor
        }
    }
}